version: "3.9"
services:
  world:
    image: yeetzone/dontstarvetogether
    container_name: world
    hostname: world
    depends_on:
      - data
    env_file:
      - env/world.env
      - env/local.env
    ports:
      - "10999:10999/udp"
      - "10888:10888/udp"
    volumes:
      - type: volume
        source: data
        target: /data
      - type: volume
        source: storage
        target: /opt/storage/
  caves:
    image: yeetzone/dontstarvetogether
    container_name: caves
    hostname: caves
    depends_on:
      - data
      - world
    env_file:
      - env/caves.env
      - env/local.env
    ports:
      - "10998:10998/udp"
    volumes:
      - type: volume
        source: data
        target: /data
      - type: volume
        source: storage
        target: /opt/storage/
  data:
    image: yeetzone/dontstarvetogether-data
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data:
  storage:
